# config/database.yml

default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: RailsJourney
  host: localhost
  port: 5433
  username: postgres
  password: a110veRJapan

test:
  <<: *default
  database: RailsJourney_test
  host: localhost
  port: 5433
  username: postgres
  password: a110veRJapan
